In [1]:
import pandas as pd
from src.api import cliente_api_aresep

In [2]:
centrales = cliente_api_aresep.ClienteAPIInformacionCentralesElectricas()

In [3]:
cent = centrales.obtener_datos(chain=False)

In [4]:
cent

,id_Objecto,operador,centralElectrica,fuente,provincia,canton,distrito,codigoDTA,coordenadaX,coordenadaY
0,1,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,PIRRÍS,HÍDRICA,SAN JOSÉ,ASERRÍ,LEGUA,10605,478245.3572,1.064996e+06
1,2,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,RÍO MACHO,HÍDRICA,CARTAGO,PARAÍSO,OROSI,30203,517366.1853,1.080929e+06
2,3,COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...,LOS SANTOS,EÓLICA,SAN JOSÉ,DESAMPARADOS,SAN CRISTOBAL,10308,500646.6299,1.081333e+06
3,4,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BARRO MORADO,HÍDRICA,CARTAGO,CARTAGO,AGUACALIENTE O SAN FRANCISCO,30105,511833.5816,1.086642e+06
4,5,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TUIS,HÍDRICA,CARTAGO,TURRIALBA,TUIS,30507,546945.2853,1.087182e+06
5,6,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS I,HÍDRICA,CARTAGO,PARAÍSO,SANTIAGO,30202,524409.3108,1.090933e+06
6,7,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,CACHÍ,HÍDRICA,CARTAGO,JIMÉNEZ,TUCURRIQUE,30402,527023.4928,1.091413e+06
7,8,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,P.E VALLE CENTRAL,EÓLICA,SAN JOSÉ,MORA,QUITIRRISÍ,10707,478191.4419,1.093821e+06
8,9,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS III,HÍDRICA,CARTAGO,ALVARADO,CAPELLADES,30603,523374.5489,1.094067e+06
9,10,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,OROTINA,COMBUSTIBLES FÓSILES,ALAJUELA,OROTINA,LA CEIBA,20905,426289.1148,1.095474e+06
10,11,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ANGOSTURA,HÍDRICA,CARTAGO,TURRIALBA,PAVONES,30506,539499.7142,1.097460e+06
11,12,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,VENTANAS,HÍDRICA,ALAJUELA,ALAJUELA,GUÁCIMA,20105,466687.8335,1.097537e+06
12,13,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ANONOS,HÍDRICA,SAN JOSÉ,SAN JOSÉ,MATA REDONDA,10108,487022.4350,1.098193e+06
13,14,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,RÍO SEGUNDO,HÍDRICA,ALAJUELA,ALAJUELA,RÍO SEGUNDO,20109,480217.5062,1.105914e+06
14,15,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,VENTANAS GARITA,HÍDRICA,ALAJUELA,ALAJUELA,TURRÚCARES,20111,460602.1713,1.098499e+06
15,16,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BRASIL,HÍDRICA,SAN JOSÉ,SANTA ANA,BRASIL,10906,474254.4070,1.099172e+06
16,17,HIDROELÉCTRICA RÍO LAJAS S.A.,HIDROELÉCTRICA RÍO LAJAS,HÍDRICA,CARTAGO,TURRIALBA,SANTA TERESITA,30505,540198.7393,1.099461e+06
17,18,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BELÉN,HÍDRICA,SAN JOSÉ,SANTA ANA,POZOS,10903,476727.3887,1.101393e+06
18,19,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SAN ANTONIO GAS,COMBUSTIBLES FÓSILES,SAN JOSÉ,SAN JOSÉ,URUCA,10107,482183.1622,1.101927e+06
19,20,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ELECTRIONA,HÍDRICA,SAN JOSÉ,SAN JOSÉ,URUCA,10107,480436.9376,1.102372e+06
20,21,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS II,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598679.4464,1.105087e+06
21,22,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS III,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598690.0261,1.105161e+06
22,23,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BARRANCA,COMBUSTIBLES FÓSILES,PUNTARENAS,PUNTARENAS,BARRANCA,60108,421604.5859,1.105217e+06
23,24,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,TACARES,HÍDRICA,ALAJUELA,GRECIA,TACARES,20305,462802.3639,1.105856e+06
24,25,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,JORGE MANUEL DENGO,HÍDRICA,ALAJUELA,POÁS,CARRILLOS,20804,470960.1970,1.109095e+06
25,26,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ECHANDI,HÍDRICA,ALAJUELA,SAN RAMÓN,PIEDADES SUR,20205,440541.7240,1.111824e+06
26,27,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,REVENTAZON,HÍDRICA,LIMÓN,SIQUIRRES,SIQUIRRES,70301,548950.8952,1.115093e+06
27,28,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,EL ENCANTO,HÍDRICA,PUNTARENAS,MONTES DE ORO,LA UNIÓN,60402,416808.9339,1.122957e+06
28,29,SUERKATA S. R. L.,SUERKATA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483140.1137,1.128513e+06
29,30,CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.,VARA BLANCA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483170.6635,1.128759e+06
30,31,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,GUÁPILES,COMBUSTIBLES FÓSILES,LIMÓN,POCOCÍ,JIMÉNEZ,70202,527457.5320,1.133652e+06
31,32,CONSORCIO COOPERATIVO CUBUJUQUI R L,CUBUJUQUÍ,HÍDRICA,HEREDIA,SARAPIQUÍ,LAS HORQUETAS,41003,505726.2009,1.137356e+06
32,33,COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...,CHOCOSUELAS,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,449348.7210,1.138330e+06
33,34,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TORO III (JASEC),HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,472943.5216,1.142816e+06
34,35,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TORO III,HÍDRICA,ALAJUELA,RÍO CUARTO,RÍO CUARTO,21601,472926.7947,1.143019e+06
35,36,HIDROELÉCTRICA CAÑO GRANDE S.A,CAÑO GRANDE,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469336.4577,1.143449e+06
36,37,INGENIO TABOGA S.A.,TABOGA,BIOMASA,GUANACASTE,CAÑAS,BEBEDERO,50604,370946.4330,1.144654e+06
37,38,EL EMBALSE S. A.,EL EMBALSE,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,453021.0728,1.144767e+06
38,39,HIDROVENECIA S.A.,HIDROVENECIA,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469109.6710,1.147055e+06
39,40,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,JUANILAMA,SOLAR,GUANACASTE,CARRILLO,BELÉN,50504,326218.0497,1.149650e+06
40,41,HIDROELÉCTRICA PLATANAR S.A.,PLATANAR,HÍDRICA,ALAJUELA,SAN CARLOS,FLORENCIA,21002,451519.8393,1.150570e+06
41,42,AZUCARERA EL VIEJO S. A.,EL VIEJO,BIOMASA,GUANACASTE,CARRILLO,FILADELFIA,50501,338108.1871,1.152386e+06
42,43,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIGUEL DENGO,HÍDRICA,GUANACASTE,CAÑAS,CAÑAS,50601,382182.9681,1.157889e+06
43,44,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ARENAL,HÍDRICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,390660.7250,1.158504e+06
44,45,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TEJONA,EÓLICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,391596.0507,1.163752e+06
45,46,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,COTE,HÍDRICA,ALAJUELA,GUATUSO,COTE,21503,389687.4879,1.179229e+06
46,47,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BOCA DE POZO,HÍDRICA,GUANACASTE,BAGACES,LA FORTUNA,50402,371659.0863,1.180815e+06
47,48,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,RIO NARANJO,EÓLICA,GUANACASTE,BAGACES,RÍO NARANJO,50404,379782.9926,1.181288e+06
48,49,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES V,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369500.0903,1.181625e+06
49,50,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES II,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369411.3671,1.183471e+06
50,51,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES I,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369361.7475,1.183521e+06
51,52,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES III,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,370762.3170,1.185388e+06
52,53,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SOLAR MIRAVALLES,SOLAR,GUANACASTE,BAGACES,LA FORTUNA,50402,370928.3087,1.185452e+06
53,54,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,LAS PAILAS,GEOTÉRMICA,GUANACASTE,LIBERIA,CURUBANDÉ,50105,348665.6060,1.187999e+06
54,55,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,BIJAGUA,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386320.3395,1.191191e+06
55,56,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,CANALETE,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386602.5221,1.193771e+06
56,57,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,368275.7219,1.200503e+06
57,58,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS II,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,370287.5237,1.203769e+06
58,59,SOLAR HUACAS,SOLAR HUACAS,SOLAR,GUANACASTE,SANTA CRUZ,TAMARINDO,50309,304429.7349,1.145262e+06
59,60,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,BIOMASA,GUANACASTE,CARRILLO,BELÉN,50504,326070.9793,1.149635e+06

In [5]:
from src.eda.ProcesadorEDA import ProcesadorEDA

In [6]:
procesador_cent = ProcesadorEDA()

In [7]:
procesador_cent.df = cent

In [8]:
procesador_cent.df

,id_Objecto,operador,centralElectrica,fuente,provincia,canton,distrito,codigoDTA,coordenadaX,coordenadaY
0,1,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,PIRRÍS,HÍDRICA,SAN JOSÉ,ASERRÍ,LEGUA,10605,478245.3572,1.064996e+06
1,2,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,RÍO MACHO,HÍDRICA,CARTAGO,PARAÍSO,OROSI,30203,517366.1853,1.080929e+06
2,3,COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...,LOS SANTOS,EÓLICA,SAN JOSÉ,DESAMPARADOS,SAN CRISTOBAL,10308,500646.6299,1.081333e+06
3,4,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BARRO MORADO,HÍDRICA,CARTAGO,CARTAGO,AGUACALIENTE O SAN FRANCISCO,30105,511833.5816,1.086642e+06
4,5,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TUIS,HÍDRICA,CARTAGO,TURRIALBA,TUIS,30507,546945.2853,1.087182e+06
5,6,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS I,HÍDRICA,CARTAGO,PARAÍSO,SANTIAGO,30202,524409.3108,1.090933e+06
6,7,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,CACHÍ,HÍDRICA,CARTAGO,JIMÉNEZ,TUCURRIQUE,30402,527023.4928,1.091413e+06
7,8,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,P.E VALLE CENTRAL,EÓLICA,SAN JOSÉ,MORA,QUITIRRISÍ,10707,478191.4419,1.093821e+06
8,9,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS III,HÍDRICA,CARTAGO,ALVARADO,CAPELLADES,30603,523374.5489,1.094067e+06
9,10,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,OROTINA,COMBUSTIBLES FÓSILES,ALAJUELA,OROTINA,LA CEIBA,20905,426289.1148,1.095474e+06
10,11,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ANGOSTURA,HÍDRICA,CARTAGO,TURRIALBA,PAVONES,30506,539499.7142,1.097460e+06
11,12,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,VENTANAS,HÍDRICA,ALAJUELA,ALAJUELA,GUÁCIMA,20105,466687.8335,1.097537e+06
12,13,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ANONOS,HÍDRICA,SAN JOSÉ,SAN JOSÉ,MATA REDONDA,10108,487022.4350,1.098193e+06
13,14,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,RÍO SEGUNDO,HÍDRICA,ALAJUELA,ALAJUELA,RÍO SEGUNDO,20109,480217.5062,1.105914e+06
14,15,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,VENTANAS GARITA,HÍDRICA,ALAJUELA,ALAJUELA,TURRÚCARES,20111,460602.1713,1.098499e+06
15,16,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BRASIL,HÍDRICA,SAN JOSÉ,SANTA ANA,BRASIL,10906,474254.4070,1.099172e+06
16,17,HIDROELÉCTRICA RÍO LAJAS S.A.,HIDROELÉCTRICA RÍO LAJAS,HÍDRICA,CARTAGO,TURRIALBA,SANTA TERESITA,30505,540198.7393,1.099461e+06
17,18,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BELÉN,HÍDRICA,SAN JOSÉ,SANTA ANA,POZOS,10903,476727.3887,1.101393e+06
18,19,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SAN ANTONIO GAS,COMBUSTIBLES FÓSILES,SAN JOSÉ,SAN JOSÉ,URUCA,10107,482183.1622,1.101927e+06
19,20,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ELECTRIONA,HÍDRICA,SAN JOSÉ,SAN JOSÉ,URUCA,10107,480436.9376,1.102372e+06
20,21,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS II,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598679.4464,1.105087e+06
21,22,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS III,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,598690.0261,1.105161e+06
22,23,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BARRANCA,COMBUSTIBLES FÓSILES,PUNTARENAS,PUNTARENAS,BARRANCA,60108,421604.5859,1.105217e+06
23,24,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,TACARES,HÍDRICA,ALAJUELA,GRECIA,TACARES,20305,462802.3639,1.105856e+06
24,25,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,JORGE MANUEL DENGO,HÍDRICA,ALAJUELA,POÁS,CARRILLOS,20804,470960.1970,1.109095e+06
25,26,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ECHANDI,HÍDRICA,ALAJUELA,SAN RAMÓN,PIEDADES SUR,20205,440541.7240,1.111824e+06
26,27,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,REVENTAZON,HÍDRICA,LIMÓN,SIQUIRRES,SIQUIRRES,70301,548950.8952,1.115093e+06
27,28,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,EL ENCANTO,HÍDRICA,PUNTARENAS,MONTES DE ORO,LA UNIÓN,60402,416808.9339,1.122957e+06
28,29,SUERKATA S. R. L.,SUERKATA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483140.1137,1.128513e+06
29,30,CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.,VARA BLANCA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,483170.6635,1.128759e+06
30,31,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,GUÁPILES,COMBUSTIBLES FÓSILES,LIMÓN,POCOCÍ,JIMÉNEZ,70202,527457.5320,1.133652e+06
31,32,CONSORCIO COOPERATIVO CUBUJUQUI R L,CUBUJUQUÍ,HÍDRICA,HEREDIA,SARAPIQUÍ,LAS HORQUETAS,41003,505726.2009,1.137356e+06
32,33,COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...,CHOCOSUELAS,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,449348.7210,1.138330e+06
33,34,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TORO III (JASEC),HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,472943.5216,1.142816e+06
34,35,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TORO III,HÍDRICA,ALAJUELA,RÍO CUARTO,RÍO CUARTO,21601,472926.7947,1.143019e+06
35,36,HIDROELÉCTRICA CAÑO GRANDE S.A,CAÑO GRANDE,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469336.4577,1.143449e+06
36,37,INGENIO TABOGA S.A.,TABOGA,BIOMASA,GUANACASTE,CAÑAS,BEBEDERO,50604,370946.4330,1.144654e+06
37,38,EL EMBALSE S. A.,EL EMBALSE,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,453021.0728,1.144767e+06
38,39,HIDROVENECIA S.A.,HIDROVENECIA,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,469109.6710,1.147055e+06
39,40,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,JUANILAMA,SOLAR,GUANACASTE,CARRILLO,BELÉN,50504,326218.0497,1.149650e+06
40,41,HIDROELÉCTRICA PLATANAR S.A.,PLATANAR,HÍDRICA,ALAJUELA,SAN CARLOS,FLORENCIA,21002,451519.8393,1.150570e+06
41,42,AZUCARERA EL VIEJO S. A.,EL VIEJO,BIOMASA,GUANACASTE,CARRILLO,FILADELFIA,50501,338108.1871,1.152386e+06
42,43,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIGUEL DENGO,HÍDRICA,GUANACASTE,CAÑAS,CAÑAS,50601,382182.9681,1.157889e+06
43,44,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ARENAL,HÍDRICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,390660.7250,1.158504e+06
44,45,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TEJONA,EÓLICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,391596.0507,1.163752e+06
45,46,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,COTE,HÍDRICA,ALAJUELA,GUATUSO,COTE,21503,389687.4879,1.179229e+06
46,47,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BOCA DE POZO,HÍDRICA,GUANACASTE,BAGACES,LA FORTUNA,50402,371659.0863,1.180815e+06
47,48,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,RIO NARANJO,EÓLICA,GUANACASTE,BAGACES,RÍO NARANJO,50404,379782.9926,1.181288e+06
48,49,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES V,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369500.0903,1.181625e+06
49,50,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES II,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369411.3671,1.183471e+06
50,51,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES I,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,369361.7475,1.183521e+06
51,52,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES III,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,370762.3170,1.185388e+06
52,53,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SOLAR MIRAVALLES,SOLAR,GUANACASTE,BAGACES,LA FORTUNA,50402,370928.3087,1.185452e+06
53,54,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,LAS PAILAS,GEOTÉRMICA,GUANACASTE,LIBERIA,CURUBANDÉ,50105,348665.6060,1.187999e+06
54,55,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,BIJAGUA,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386320.3395,1.191191e+06
55,56,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,CANALETE,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,386602.5221,1.193771e+06
56,57,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,368275.7219,1.200503e+06
57,58,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS II,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,370287.5237,1.203769e+06
58,59,SOLAR HUACAS,SOLAR HUACAS,SOLAR,GUANACASTE,SANTA CRUZ,TAMARINDO,50309,304429.7349,1.145262e+06
59,60,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,BIOMASA,GUANACASTE,CARRILLO,BELÉN,50504,326070.9793,1.149635e+06

In [9]:
procesador_cent.verif_consis(chain=False)

({'id_Objecto': int,
  'operador': str,
  'centralElectrica': str,
  'fuente': str,
  'provincia': str,
  'canton': str,
  'distrito': str,
  'codigoDTA': str,
  'coordenadaX': float,
  'coordenadaY': float},
 {})

In [10]:
procesador_cent.param_set()

{'Numero de filas': 60,
 'Numero de columnas': 10,
 'Porcentaje de nulos': 0.0,
 'Ceros totales': 0,
 'Dataframe':     id_Objecto                                           operador  \
 0            1            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 1            2            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 2            3  COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...
 3            4  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 4            5  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 5            6  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 6            7            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 7            8             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 8            9  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 9           10            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 10          11            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 11          12             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 12          13             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 13          14             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 14          15            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 15          16             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 16          17                      HIDROELÉCTRICA RÍO LAJAS S.A.
 17          18             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 18          19            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 19          20             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 20          21            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 21          22            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 22          23            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 23          24      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 24          25      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 25          26            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 26          27            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 27          28             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 28          29                                  SUERKATA S. R. L.
 29          30           CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.
 30          31            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 31          32                CONSORCIO COOPERATIVO CUBUJUQUI R L
 32          33  COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...
 33          34  JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...
 34          35            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 35          36                     HIDROELÉCTRICA CAÑO GRANDE S.A
 36          37                                INGENIO TABOGA S.A.
 37          38                                   EL EMBALSE S. A.
 38          39                                  HIDROVENECIA S.A.
 39          40  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 40          41                       HIDROELÉCTRICA PLATANAR S.A.
 41          42                           AZUCARERA EL VIEJO S. A.
 42          43            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 43          44            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 44          45            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 45          46             COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.
 46          47            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 47          48  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 48          49            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 49          50            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 50          51            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 51          52            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 52          53            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 53          54            INSTITUTO COSTARRICENSE DE ELECTRICIDAD
 54          55  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 55          56  COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...
 56          57      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 57          58      EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.
 58          59                                       SOLAR HUACAS
 59          60          GASIFICACION RESIDUOS SOLIDOS MUNICIPALES

                              centralElectrica                fuente  \
 0                                      PIRRÍS               HÍDRICA
 1                                   RÍO MACHO               HÍDRICA
 2                                  LOS SANTOS                EÓLICA
 3                                BARRO MORADO               HÍDRICA
 4                                        TUIS               HÍDRICA
 5                                    BIRRIS I               HÍDRICA
 6                                       CACHÍ               HÍDRICA
 7                           P.E VALLE CENTRAL                EÓLICA
 8                                  BIRRIS III               HÍDRICA
 9                                     OROTINA  COMBUSTIBLES FÓSILES
 10                                  ANGOSTURA               HÍDRICA
 11                                   VENTANAS               HÍDRICA
 12                                     ANONOS               HÍDRICA
 13                                RÍO SEGUNDO               HÍDRICA
 14                            VENTANAS GARITA               HÍDRICA
 15                                     BRASIL               HÍDRICA
 16                   HIDROELÉCTRICA RÍO LAJAS               HÍDRICA
 17                                      BELÉN               HÍDRICA
 18                            SAN ANTONIO GAS  COMBUSTIBLES FÓSILES
 19                                 ELECTRIONA               HÍDRICA
 20                                MOÍN GAS II  COMBUSTIBLES FÓSILES
 21                               MOÍN GAS III  COMBUSTIBLES FÓSILES
 22                                   BARRANCA  COMBUSTIBLES FÓSILES
 23                                    TACARES               HÍDRICA
 24                         JORGE MANUEL DENGO               HÍDRICA
 25                                    ECHANDI               HÍDRICA
 26                                 REVENTAZON               HÍDRICA
 27                                 EL ENCANTO               HÍDRICA
 28                                   SUERKATA               HÍDRICA
 29                                VARA BLANCA               HÍDRICA
 30                                   GUÁPILES  COMBUSTIBLES FÓSILES
 31                                  CUBUJUQUÍ               HÍDRICA
 32                                CHOCOSUELAS               HÍDRICA
 33                           TORO III (JASEC)               HÍDRICA
 34                                   TORO III               HÍDRICA
 35                                CAÑO GRANDE               HÍDRICA
 36                                     TABOGA               BIOMASA
 37                                 EL EMBALSE               HÍDRICA
 38                               HIDROVENECIA               HÍDRICA
 39                                  JUANILAMA                 SOLAR
 40                                   PLATANAR               HÍDRICA
 41                                   EL VIEJO               BIOMASA
 42                               MIGUEL DENGO               HÍDRICA
 43                                     ARENAL               HÍDRICA
 44                                     TEJONA                EÓLICA
 45                                       COTE               HÍDRICA
 46                               BOCA DE POZO               HÍDRICA
 47                                RIO NARANJO                EÓLICA
 48                               MIRAVALLES V            GEOTÉRMICA
 49                              MIRAVALLES II            GEOTÉRMICA
 50                               MIRAVALLES I            GEOTÉRMICA
 51                             MIRAVALLES III            GEOTÉRMICA
 52                           SOLAR MIRAVALLES                 SOLAR
 53                                 LAS PAILAS            GEOTÉRMICA
 54                                    BIJAGUA               HÍDRICA
 55                                   CANALETE               HÍDRICA
 56                                 LOS NEGROS               HÍDRICA
 57                              LOS NEGROS II               HÍDRICA
 58                               SOLAR HUACAS                 SOLAR
 59  GASIFICACION RESIDUOS SOLIDOS MUNICIPALES               BIOMASA

      provincia         canton                      distrito codigoDTA  \
 0     SAN JOSÉ         ASERRÍ                         LEGUA     10605
 1      CARTAGO        PARAÍSO                         OROSI     30203
 2     SAN JOSÉ   DESAMPARADOS                 SAN CRISTOBAL     10308
 3      CARTAGO        CARTAGO  AGUACALIENTE O SAN FRANCISCO     30105
 4      CARTAGO      TURRIALBA                          TUIS     30507
 5      CARTAGO        PARAÍSO                      SANTIAGO     30202
 6      CARTAGO        JIMÉNEZ                    TUCURRIQUE     30402
 7     SAN JOSÉ           MORA                    QUITIRRISÍ     10707
 8      CARTAGO       ALVARADO                    CAPELLADES     30603
 9     ALAJUELA        OROTINA                      LA CEIBA     20905
 10     CARTAGO      TURRIALBA                       PAVONES     30506
 11    ALAJUELA       ALAJUELA                       GUÁCIMA     20105
 12    SAN JOSÉ       SAN JOSÉ                  MATA REDONDA     10108
 13    ALAJUELA       ALAJUELA                   RÍO SEGUNDO     20109
 14    ALAJUELA       ALAJUELA                    TURRÚCARES     20111
 15    SAN JOSÉ      SANTA ANA                        BRASIL     10906
 16     CARTAGO      TURRIALBA                SANTA TERESITA     30505
 17    SAN JOSÉ      SANTA ANA                         POZOS     10903
 18    SAN JOSÉ       SAN JOSÉ                         URUCA     10107
 19    SAN JOSÉ       SAN JOSÉ                         URUCA     10107
 20       LIMÓN          LIMÓN                    RÍO BLANCO     70103
 21       LIMÓN          LIMÓN                    RÍO BLANCO     70103
 22  PUNTARENAS     PUNTARENAS                      BARRANCA     60108
 23    ALAJUELA         GRECIA                       TACARES     20305
 24    ALAJUELA           POÁS                     CARRILLOS     20804
 25    ALAJUELA      SAN RAMÓN                  PIEDADES SUR     20205
 26       LIMÓN      SIQUIRRES                     SIQUIRRES     70301
 27  PUNTARENAS  MONTES DE ORO                      LA UNIÓN     60402
 28     HEREDIA        HEREDIA                    VARABLANCA     40105
 29     HEREDIA        HEREDIA                    VARABLANCA     40105
 30       LIMÓN         POCOCÍ                       JIMÉNEZ     70202
 31     HEREDIA      SARAPIQUÍ                 LAS HORQUETAS     41003
 32    ALAJUELA     SAN CARLOS                       QUESADA     21001
 33    ALAJUELA     SAN CARLOS                       VENECIA     21005
 34    ALAJUELA     RÍO CUARTO                    RÍO CUARTO     21601
 35    ALAJUELA     SAN CARLOS                       VENECIA     21005
 36  GUANACASTE          CAÑAS                      BEBEDERO     50604
 37    ALAJUELA     SAN CARLOS                       QUESADA     21001
 38    ALAJUELA     SAN CARLOS                       VENECIA     21005
 39  GUANACASTE       CARRILLO                         BELÉN     50504
 40    ALAJUELA     SAN CARLOS                     FLORENCIA     21002
 41  GUANACASTE       CARRILLO                    FILADELFIA     50501
 42  GUANACASTE          CAÑAS                         CAÑAS     50601
 43  GUANACASTE        TILARÁN                    SANTA ROSA     50804
 44  GUANACASTE        TILARÁN                    SANTA ROSA     50804
 45    ALAJUELA        GUATUSO                          COTE     21503
 46  GUANACASTE        BAGACES                    LA FORTUNA     50402
 47  GUANACASTE        BAGACES                   RÍO NARANJO     50404
 48  GUANACASTE        BAGACES                    LA FORTUNA     50402
 49  GUANACASTE        BAGACES                    LA FORTUNA     50402
 50  GUANACASTE        BAGACES                    LA FORTUNA     50402
 51  GUANACASTE        BAGACES                    LA FORTUNA     50402
 52  GUANACASTE        BAGACES                    LA FORTUNA     50402
 53  GUANACASTE        LIBERIA                     CURUBANDÉ     50105
 54    ALAJUELA          UPALA                       BIJAGUA     21304
 55    ALAJUELA          UPALA                       BIJAGUA     21304
 56    ALAJUELA          UPALA                  AGUAS CLARAS     21302
 57    ALAJUELA          UPALA                  AGUAS CLARAS     21302
 58  GUANACASTE     SANTA CRUZ                     TAMARINDO     50309
 59  GUANACASTE       CARRILLO                         BELÉN     50504

     coordenadaX   coordenadaY
 0   478245.3572  1.064996e+06
 1   517366.1853  1.080929e+06
 2   500646.6299  1.081333e+06
 3   511833.5816  1.086642e+06
 4   546945.2853  1.087182e+06
 5   524409.3108  1.090933e+06
 6   527023.4928  1.091413e+06
 7   478191.4419  1.093821e+06
 8   523374.5489  1.094067e+06
 9   426289.1148  1.095474e+06
 10  539499.7142  1.097460e+06
 11  466687.8335  1.097537e+06
 12  487022.4350  1.098193e+06
 13  480217.5062  1.105914e+06
 14  460602.1713  1.098499e+06
 15  474254.4070  1.099172e+06
 16  540198.7393  1.099461e+06
 17  476727.3887  1.101393e+06
 18  482183.1622  1.101927e+06
 19  480436.9376  1.102372e+06
 20  598679.4464  1.105087e+06
 21  598690.0261  1.105161e+06
 22  421604.5859  1.105217e+06
 23  462802.3639  1.105856e+06
 24  470960.1970  1.109095e+06
 25  440541.7240  1.111824e+06
 26  548950.8952  1.115093e+06
 27  416808.9339  1.122957e+06
 28  483140.1137  1.128513e+06
 29  483170.6635  1.128759e+06
 30  527457.5320  1.133652e+06
 31  505726.2009  1.137356e+06
 32  449348.7210  1.138330e+06
 33  472943.5216  1.142816e+06
 34  472926.7947  1.143019e+06
 35  469336.4577  1.143449e+06
 36  370946.4330  1.144654e+06
 37  453021.0728  1.144767e+06
 38  469109.6710  1.147055e+06
 39  326218.0497  1.149650e+06
 40  451519.8393  1.150570e+06
 41  338108.1871  1.152386e+06
 42  382182.9681  1.157889e+06
 43  390660.7250  1.158504e+06
 44  391596.0507  1.163752e+06
 45  389687.4879  1.179229e+06
 46  371659.0863  1.180815e+06
 47  379782.9926  1.181288e+06
 48  369500.0903  1.181625e+06
 49  369411.3671  1.183471e+06
 50  369361.7475  1.183521e+06
 51  370762.3170  1.185388e+06
 52  370928.3087  1.185452e+06
 53  348665.6060  1.187999e+06
 54  386320.3395  1.191191e+06
 55  386602.5221  1.193771e+06
 56  368275.7219  1.200503e+06
 57  370287.5237  1.203769e+06
 58  304429.7349  1.145262e+06
 59  326070.9793  1.149635e+06  }

In [11]:
procesador_cent.convert_lon_lat(col_lon="coordenadaX",col_lat="coordenadaY", chain=False)

,id_Objecto,operador,centralElectrica,fuente,provincia,canton,distrito,codigoDTA,coordenadaX,coordenadaY
0,1,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,PIRRÍS,HÍDRICA,SAN JOSÉ,ASERRÍ,LEGUA,10605,-84.198220,9.631497
1,2,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,RÍO MACHO,HÍDRICA,CARTAGO,PARAÍSO,OROSI,30203,-83.841698,9.775583
2,3,COOPERATIVA DE ELECTRIFICACION RURAL LOS SANTO...,LOS SANTOS,EÓLICA,SAN JOSÉ,DESAMPARADOS,SAN CRISTOBAL,10308,-83.994106,9.779272
3,4,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BARRO MORADO,HÍDRICA,CARTAGO,CARTAGO,AGUACALIENTE O SAN FRANCISCO,30105,-83.892114,9.827261
4,5,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TUIS,HÍDRICA,CARTAGO,TURRIALBA,TUIS,30507,-83.572000,9.831892
5,6,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS I,HÍDRICA,CARTAGO,PARAÍSO,SANTIAGO,30202,-83.777436,9.866008
6,7,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,CACHÍ,HÍDRICA,CARTAGO,JIMÉNEZ,TUCURRIQUE,30402,-83.753597,9.870327
7,8,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,P.E VALLE CENTRAL,EÓLICA,SAN JOSÉ,MORA,QUITIRRISÍ,10707,-84.198866,9.892130
8,9,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,BIRRIS III,HÍDRICA,CARTAGO,ALVARADO,CAPELLADES,30603,-83.786853,9.894347
9,10,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,OROTINA,COMBUSTIBLES FÓSILES,ALAJUELA,OROTINA,LA CEIBA,20905,-84.672164,9.906468
10,11,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ANGOSTURA,HÍDRICA,CARTAGO,TURRIALBA,PAVONES,30506,-83.639779,9.924899
11,12,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,VENTANAS,HÍDRICA,ALAJUELA,ALAJUELA,GUÁCIMA,20105,-84.303794,9.925651
12,13,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ANONOS,HÍDRICA,SAN JOSÉ,SAN JOSÉ,MATA REDONDA,10108,-84.118353,9.931705
13,14,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,RÍO SEGUNDO,HÍDRICA,ALAJUELA,ALAJUELA,RÍO SEGUNDO,20109,-84.180451,10.001487
14,15,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,VENTANAS GARITA,HÍDRICA,ALAJUELA,ALAJUELA,TURRÚCARES,20111,-84.359302,9.934299
15,16,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BRASIL,HÍDRICA,SAN JOSÉ,SANTA ANA,BRASIL,10906,-84.234801,9.940495
16,17,HIDROELÉCTRICA RÍO LAJAS S.A.,HIDROELÉCTRICA RÍO LAJAS,HÍDRICA,CARTAGO,TURRIALBA,SANTA TERESITA,30505,-83.633384,9.942983
17,18,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,BELÉN,HÍDRICA,SAN JOSÉ,SANTA ANA,POZOS,10903,-84.212260,9.960590
18,19,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SAN ANTONIO GAS,COMBUSTIBLES FÓSILES,SAN JOSÉ,SAN JOSÉ,URUCA,10107,-84.162503,9.965443
19,20,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,ELECTRIONA,HÍDRICA,SAN JOSÉ,SAN JOSÉ,URUCA,10107,-84.178432,9.969458
20,21,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS II,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,-83.099928,9.992841
21,22,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MOÍN GAS III,COMBUSTIBLES FÓSILES,LIMÓN,LIMÓN,RÍO BLANCO,70103,-83.099830,9.993511
22,23,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BARRANCA,COMBUSTIBLES FÓSILES,PUNTARENAS,PUNTARENAS,BARRANCA,60108,-84.715072,9.994467
23,24,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,TACARES,HÍDRICA,ALAJUELA,GRECIA,TACARES,20305,-84.339306,10.000833
24,25,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,JORGE MANUEL DENGO,HÍDRICA,ALAJUELA,POÁS,CARRILLOS,20804,-84.264917,10.030194
25,26,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ECHANDI,HÍDRICA,ALAJUELA,SAN RAMÓN,PIEDADES SUR,20205,-84.542445,10.054529
26,27,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,REVENTAZON,HÍDRICA,LIMÓN,SIQUIRRES,SIQUIRRES,70301,-83.553372,10.084229
27,28,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,EL ENCANTO,HÍDRICA,PUNTARENAS,MONTES DE ORO,LA UNIÓN,60402,-84.759187,10.154755
28,29,SUERKATA S. R. L.,SUERKATA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,-84.153889,10.205833
29,30,CENTRAL HIDROELÉCTRICA VARA BLANCA S. A.,VARA BLANCA,HÍDRICA,HEREDIA,HEREDIA,VARABLANCA,40105,-84.153611,10.208056
30,31,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,GUÁPILES,COMBUSTIBLES FÓSILES,LIMÓN,POCOCÍ,JIMÉNEZ,70202,-83.749345,10.252242
31,32,CONSORCIO COOPERATIVO CUBUJUQUI R L,CUBUJUQUÍ,HÍDRICA,HEREDIA,SARAPIQUÍ,LAS HORQUETAS,41003,-83.947721,10.285824
32,33,COOPERATIVA DE ELECTRIFICACION RURAL DE SAN CA...,CHOCOSUELAS,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,-84.462444,10.294306
33,34,JUNTA ADMINISTRATIVA DEL SERVICIO ELECTRICO MU...,TORO III (JASEC),HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,-84.247058,10.335100
34,35,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TORO III,HÍDRICA,ALAJUELA,RÍO CUARTO,RÍO CUARTO,21601,-84.247213,10.336931
35,36,HIDROELÉCTRICA CAÑO GRANDE S.A,CAÑO GRANDE,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,-84.280000,10.340800
36,37,INGENIO TABOGA S.A.,TABOGA,BIOMASA,GUANACASTE,CAÑAS,BEBEDERO,50604,-85.178394,10.349656
37,38,EL EMBALSE S. A.,EL EMBALSE,HÍDRICA,ALAJUELA,SAN CARLOS,QUESADA,21001,-84.428996,10.352552
38,39,HIDROVENECIA S.A.,HIDROVENECIA,HÍDRICA,ALAJUELA,SAN CARLOS,VENECIA,21005,-84.282100,10.373400
39,40,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,JUANILAMA,SOLAR,GUANACASTE,CARRILLO,BELÉN,50504,-85.586944,10.393056
40,41,HIDROELÉCTRICA PLATANAR S.A.,PLATANAR,HÍDRICA,ALAJUELA,SAN CARLOS,FLORENCIA,21002,-84.442778,10.405000
41,42,AZUCARERA EL VIEJO S. A.,EL VIEJO,BIOMASA,GUANACASTE,CARRILLO,FILADELFIA,50501,-85.478508,10.418306
42,43,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIGUEL DENGO,HÍDRICA,GUANACASTE,CAÑAS,CAÑAS,50601,-85.076216,10.469664
43,44,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,ARENAL,HÍDRICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,-84.998801,10.475477
44,45,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,TEJONA,EÓLICA,GUANACASTE,TILARÁN,SANTA ROSA,50804,-84.990409,10.522939
45,46,COMPAÑIA NACIONAL DE FUERZA Y LUZ S.A.,COTE,HÍDRICA,ALAJUELA,GUATUSO,COTE,21503,-85.008302,10.662804
46,47,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,BOCA DE POZO,HÍDRICA,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.173122,10.676568
47,48,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,RIO NARANJO,EÓLICA,GUANACASTE,BAGACES,RÍO NARANJO,50404,-85.098889,10.681111
48,49,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES V,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.192882,10.683812
49,50,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES II,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.193758,10.700496
50,51,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES I,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.194213,10.700942
51,52,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,MIRAVALLES III,GEOTÉRMICA,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.181478,10.717868
52,53,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,SOLAR MIRAVALLES,SOLAR,GUANACASTE,BAGACES,LA FORTUNA,50402,-85.179963,10.718456
53,54,INSTITUTO COSTARRICENSE DE ELECTRICIDAD,LAS PAILAS,GEOTÉRMICA,GUANACASTE,LIBERIA,CURUBANDÉ,50105,-85.383553,10.740641
54,55,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,BIJAGUA,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,-85.039444,10.770833
55,56,COOPERATIVA DE ELECTRIFICACION RURAL DE GUANAC...,CANALETE,HÍDRICA,ALAJUELA,UPALA,BIJAGUA,21304,-85.036944,10.794167
56,57,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,-85.204750,10.854417
57,58,EMPRESA DE SERVICIOS PUBLICOS DE HEREDIA S.A.,LOS NEGROS II,HÍDRICA,ALAJUELA,UPALA,AGUAS CLARAS,21302,-85.186469,10.884006
58,59,SOLAR HUACAS,SOLAR HUACAS,SOLAR,GUANACASTE,SANTA CRUZ,TAMARINDO,50309,-85.785623,10.352357
59,60,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,GASIFICACION RESIDUOS SOLIDOS MUNICIPALES,BIOMASA,GUANACASTE,CARRILLO,BELÉN,50504,-85.588286,10.392916

In [12]:
procesador_cent.save_df("processed/aresep_apis/Centro", chain=False)